export const GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST'
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS'
export const GET_FLIGHTS_ERROR = 'GET_FLIGHTS_ERROR'
export const FILTER_FLIGHTS_BY_CARRIER = 'FILTER_FLIGHTS_BY_CARRIER'
